name: CI

on:

  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches: [ "main" ]

jobs:
  check_PR_message:
    runs-on: ubuntu-latest

    steps:
    - uses: robin-thomas-e1391/PR-title-validator@master
      with:
          regex: 'JIRA|Mira' # Regex the title should match.
          regex_options: 'i' # Regex should be case insensitive.
          custom_non_match_error: 'valid title options are ... JIRA, Mira'

