name: CI

on:

  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches: [ "main" ]

jobs:
  check_PR_message:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR labels action step
        uses: Slashgear/action-check-pr-title@2.0.0
        with:
            regex: '([a-z])+'
            github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Run a one-line script
        run: pwd

